version: 2.1  # Defines the CircleCI configuration version

orbs:
  python: circleci/python@2.1.1  # Uses the Python orb

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.7  # Docker container with Python 3.10
    steps:
      - checkout  # Checkout the code from the repository
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt  # Installs the dependencies

      # Debugging: Show current path and directory structure
      - run:
          name: Debug current working directory
          command: |
            pwd
            ls
        
      # Run tests one by one, with separate commands for each test file
      - run:
          name: Run tests for hyperparameters.py
          command: python -m unittest tests.hyperparameters_test 

      - run:
          name: Run tests for utils.py
          command: python -m unittest tests.utils_test 

      - run:
          name: Run tests for data_class.py
          command: python -m unittest tests.data_class_test

      - run:
          name: Run tests for model_class.py
          command: python -m unittest tests.model_class_test

workflows:
  version: 2  # Workflow version
  test:
    jobs:
      - build-and-test  # Run the 'build-and-test' job

